services:
  # === Base de données PostgreSQL ===
  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # === Interface PGAdmin ===
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db

  # === Backend Express ===
  backend:
    build: ./backend
    container_name: backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5001:5001"
    depends_on:
      - db

  # === Frontend React ===
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  # === Test Runner (Node.js) ===
  test-runner:
    build:
      context: ./selenium
      dockerfile: Dockerfile
    container_name: test-runner
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "4000:4000"
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-hub:4444/wd/hub

  # === Selenium Grid Hub ===
  selenium-hub:
    image: selenium/hub:4.21.0-20240521
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=10
      - SE_SESSION_REQUEST_TIMEOUT=60
      - SE_SESSION_RETRY_INTERVAL=2

  # === Node Chrome ===
  chrome-node:
    image: selenium/node-chrome:4.21.0-20240521
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: 2g

volumes:
  pg_data: